# Generated by Django 5.0.3 on 2024-05-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
