# Generated by Django 5.0.4 on 2024-05-20 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_order_customer_order_user'),
        ('product', '0009_alter_review_options_alter_subcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='customer_or_id_596198_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitems',
            index=models.Index(fields=['id'], name='customer_or_id_3b59aa_idx'),
        ),
    ]
