# Generated by Django 5.0.4 on 2024-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
