# Generated by Django 5.0.3 on 2024-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_discount_price_product_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
