# Generated by Django 5.0.3 on 2024-05-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_data_added_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
