# Generated by Django 5.0.4 on 2024-05-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
