# Generated by Django 5.0.4 on 2024-05-20 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['id'], name='product_rev_id_80e37e_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['id'], name='product_sub_id_07155b_idx'),
        ),
    ]
