# Generated by Django 5.0.4 on 2024-05-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='tel_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
